version: '2'

volumes:
  sandbox-redis-data:
    driver: local

services:
  mongo:
    image: 'mongo'
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: sandbox

  app:
    build: .
    container_name: adonis
    depends_on:
      - 'mongo'
    volumes:
      - ./app:/src
    ports:
      - "7700:3333"
    links:
      - mongo
    command:
      "adonis serve --dev"